-- ============================================================
-- Aurora — Seed: 365 Palabras del Día
-- Organizadas temáticamente y alineadas al currículo A1→B2
-- Días   1-60:  A1 — Básicos, saludos, familia, rutina
-- Días  61-120: A2 — Pasado, lugares, emociones, tiempo
-- Días 121-180: B1 — Condicionales, opiniones, trabajo, viajes
-- Días 181-240: B1+ — Matices, conectores, habilidades blandas
-- Días 241-300: B2 — Expresiones complejas, registro formal
-- Días 301-365: B2+ — Vocabulario académico y profesional
-- ============================================================

DELETE FROM words_of_day;

INSERT INTO words_of_day (day_of_year, word, translation, part_of_speech, example, example_es, phonetic) VALUES

-- ─── A1: Saludos y presentaciones (1-10) ───────────────────
(1,  'hello',      'hola',           'interjection', 'Hello! My name is Naye.',                    'Hola, me llamo Naye.',                        'he-LOU'),
(2,  'goodbye',    'adiós',          'interjection', 'Goodbye! See you tomorrow.',                 'Adiós, hasta mañana.',                        'gud-BAI'),
(3,  'please',     'por favor',      'adverb',       'Can you help me, please?',                   '¿Me puedes ayudar, por favor?',               'PLIIS'),
(4,  'thank you',  'gracias',        'phrase',       'Thank you for your help.',                   'Gracias por tu ayuda.',                       'ZANK-yu'),
(5,  'sorry',      'lo siento',      'interjection', 'Sorry, I did not understand.',               'Lo siento, no entendí.',                      'SO-ri'),
(6,  'yes',        'sí',             'adverb',       'Yes, I speak a little English.',             'Sí, hablo un poco de inglés.',                'YES'),
(7,  'no',         'no',             'adverb',       'No, that is not correct.',                   'No, eso no es correcto.',                     'NOU'),
(8,  'name',       'nombre',         'noun',         'My name is Ana.',                            'Mi nombre es Ana.',                           'NEIM'),
(9,  'friend',     'amigo / amiga',  'noun',         'She is my best friend.',                     'Ella es mi mejor amiga.',                     'FREND'),
(10, 'nice',       'agradable',      'adjective',    'Nice to meet you!',                          'Mucho gusto.',                                'NAIS'),

-- ─── A1: Pronombres y verbo To Be (11-20) ──────────────────
(11, 'I',          'yo',             'pronoun',      'I am a student.',                            'Yo soy estudiante.',                          'AI'),
(12, 'you',        'tú / usted',     'pronoun',      'You are very kind.',                         'Tú eres muy amable.',                         'YUU'),
(13, 'he',         'él',             'pronoun',      'He is my brother.',                          'Él es mi hermano.',                           'JI'),
(14, 'she',        'ella',           'pronoun',      'She is a doctor.',                           'Ella es doctora.',                            'ŠI'),
(15, 'we',         'nosotros',       'pronoun',      'We are from Mexico.',                        'Somos de México.',                            'UÍ'),
(16, 'they',       'ellos / ellas',  'pronoun',      'They are my friends.',                       'Ellos son mis amigos.',                       'DEI'),
(17, 'am',         'soy / estoy',    'verb',         'I am happy today.',                          'Estoy feliz hoy.',                            'AM'),
(18, 'is',         'es / está',      'verb',         'She is my teacher.',                         'Ella es mi maestra.',                         'IS'),
(19, 'are',        'son / están',    'verb',         'They are at school.',                        'Ellos están en la escuela.',                  'AR'),
(20, 'not',        'no (negación)',  'adverb',       'I am not tired.',                            'No estoy cansada.',                           'NOT'),

-- ─── A1: Familia (21-30) ───────────────────────────────────
(21, 'mother',     'madre',          'noun',         'My mother is very funny.',                   'Mi madre es muy graciosa.',                   'MA-der'),
(22, 'father',     'padre',          'noun',         'My father works in an office.',              'Mi padre trabaja en una oficina.',             'FA-der'),
(23, 'brother',    'hermano',        'noun',         'My brother loves soccer.',                   'A mi hermano le encanta el fútbol.',          'BRA-der'),
(24, 'sister',     'hermana',        'noun',         'My sister is five years old.',               'Mi hermana tiene cinco años.',                'SIS-ter'),
(25, 'family',     'familia',        'noun',         'I love my family very much.',                'Quiero mucho a mi familia.',                  'FA-mi-li'),
(26, 'son',        'hijo',           'noun',         'Her son is a great student.',                'Su hijo es un gran estudiante.',              'SON'),
(27, 'daughter',   'hija',           'noun',         'Their daughter speaks three languages.',     'Su hija habla tres idiomas.',                 'DO-ter'),
(28, 'husband',    'esposo',         'noun',         'Her husband is a chef.',                     'Su esposo es chef.',                          'JAS-bend'),
(29, 'wife',       'esposa',         'noun',         'His wife is a teacher.',                     'Su esposa es maestra.',                       'UAIF'),
(30, 'baby',       'bebé',           'noun',         'The baby is sleeping.',                      'El bebé está durmiendo.',                     'BEI-bi'),

-- ─── A1: Colores y objetos (31-40) ─────────────────────────
(31, 'red',        'rojo',           'adjective',    'The apple is red.',                          'La manzana es roja.',                         'RED'),
(32, 'blue',       'azul',           'adjective',    'The sky is blue.',                           'El cielo es azul.',                           'BLUU'),
(33, 'green',      'verde',          'adjective',    'The grass is green.',                        'El pasto es verde.',                          'GRIIN'),
(34, 'white',      'blanco',         'adjective',    'The walls are white.',                       'Las paredes son blancas.',                    'UAIT'),
(35, 'black',      'negro',          'adjective',    'Her cat is black.',                          'Su gato es negro.',                           'BLAK'),
(36, 'book',       'libro',          'noun',         'I read a book every week.',                  'Leo un libro cada semana.',                   'BUK'),
(37, 'door',       'puerta',         'noun',         'Please close the door.',                     'Por favor cierra la puerta.',                 'DOR'),
(38, 'table',      'mesa',           'noun',         'The food is on the table.',                  'La comida está en la mesa.',                  'TEI-bol'),
(39, 'chair',      'silla',          'noun',         'Please take a chair.',                       'Por favor toma asiento.',                     'CHER'),
(40, 'window',     'ventana',        'noun',         'Open the window, please.',                   'Abre la ventana, por favor.',                 'WIN-dou'),

-- ─── A1: Comida y bebida (41-50) ───────────────────────────
(41, 'water',      'agua',           'noun',         'I drink water every day.',                   'Bebo agua todos los días.',                   'UO-ter'),
(42, 'food',       'comida',         'noun',         'Mexican food is delicious.',                 'La comida mexicana es deliciosa.',            'FUUD'),
(43, 'eat',        'comer',          'verb',         'I eat breakfast at seven.',                  'Desayuno a las siete.',                       'IIT'),
(44, 'drink',      'beber',          'verb',         'She drinks coffee every morning.',           'Ella toma café cada mañana.',                 'DRINK'),
(45, 'breakfast',  'desayuno',       'noun',         'Breakfast is my favorite meal.',             'El desayuno es mi comida favorita.',          'BREK-fest'),
(46, 'lunch',      'almuerzo',       'noun',         'We have lunch at one o''clock.',             'Almorzamos a la una.',                        'LANCH'),
(47, 'dinner',     'cena',           'noun',         'Dinner is at eight in my house.',            'La cena es a las ocho en mi casa.',           'DI-ner'),
(48, 'apple',      'manzana',        'noun',         'An apple a day keeps the doctor away.',      'Una manzana al día mantiene al médico lejos.','A-pol'),
(49, 'rice',       'arroz',          'noun',         'We eat rice with every meal.',               'Comemos arroz en cada comida.',               'RAIS'),
(50, 'bread',      'pan',            'noun',         'Fresh bread smells amazing.',                'El pan fresco huele increíble.',              'BRED'),

-- ─── A1: Rutina diaria y tiempo (51-60) ────────────────────
(51, 'morning',    'mañana',         'noun',         'I exercise every morning.',                  'Hago ejercicio cada mañana.',                 'MOR-ning'),
(52, 'afternoon',  'tarde',          'noun',         'We study in the afternoon.',                 'Estudiamos por la tarde.',                    'af-ter-NUUN'),
(53, 'night',      'noche',          'noun',         'I read at night.',                           'Leo por las noches.',                         'NAIT'),
(54, 'today',      'hoy',            'adverb',       'Today is a great day.',                      'Hoy es un gran día.',                         'tu-DEI'),
(55, 'tomorrow',   'mañana (futuro)','adverb',       'Tomorrow we have class.',                    'Mañana tenemos clase.',                       'tu-MO-rou'),
(56, 'every day',  'todos los días', 'phrase',       'I practice English every day.',              'Practico inglés todos los días.',             'E-vri-dei'),
(57, 'go',         'ir',             'verb',         'I go to school by bus.',                     'Voy a la escuela en autobús.',                'GOU'),
(58, 'work',       'trabajar',       'verb',         'She works in a hospital.',                   'Ella trabaja en un hospital.',                'UORK'),
(59, 'sleep',      'dormir',         'verb',         'I sleep eight hours a day.',                 'Duermo ocho horas al día.',                   'SLIIP'),
(60, 'wake up',    'despertar',      'phrase',       'I wake up at six every day.',                'Me despierto a las seis todos los días.',     'UEIK-ap'),

-- ─── A2: Pasado simple (61-75) ─────────────────────────────
(61, 'yesterday',  'ayer',           'adverb',       'Yesterday I studied for two hours.',         'Ayer estudié dos horas.',                     'YES-ter-dei'),
(62, 'last week',  'la semana pasada','phrase',      'Last week I visited my grandmother.',        'La semana pasada visité a mi abuela.',        'LAST-wiik'),
(63, 'ago',        'hace (tiempo)',  'adverb',       'I moved here two years ago.',                'Me mudé aquí hace dos años.',                 'a-GOU'),
(64, 'went',       'fue / fui',      'verb',         'She went to the market yesterday.',          'Ella fue al mercado ayer.',                   'WENT'),
(65, 'said',       'dijo / dije',    'verb',         'He said hello to everyone.',                 'Él le dijo hola a todos.',                    'SED'),
(66, 'saw',        'vio / vi',       'verb',         'I saw a beautiful sunset.',                  'Vi un atardecer hermoso.',                    'SO'),
(67, 'got',        'obtuvo / obtuve','verb',         'She got a new job last month.',              'Ella consiguió un nuevo trabajo el mes pasado.','GOT'),
(68, 'made',       'hizo / hice',    'verb',         'I made tamales for Christmas.',              'Hice tamales para Navidad.',                  'MEID'),
(69, 'came',       'vino / vine',    'verb',         'He came home very late.',                    'Él llegó a casa muy tarde.',                  'KEIM'),
(70, 'took',       'tomó / tomé',    'verb',         'She took a taxi to the airport.',            'Ella tomó un taxi al aeropuerto.',            'TUK'),
(71, 'found',      'encontró / encontré','verb',     'I found my keys under the couch.',           'Encontré mis llaves debajo del sofá.',        'FAUND'),
(72, 'bought',     'compró / compré','verb',         'We bought vegetables at the market.',        'Compramos verduras en el mercado.',           'BOT'),
(73, 'told',       'contó / conté',  'verb',         'She told me an interesting story.',          'Ella me contó una historia interesante.',     'TOLD'),
(74, 'thought',    'pensó / pensé',  'verb',         'I thought the movie was great.',             'Pensé que la película era genial.',           'ZOT'),
(75, 'knew',       'sabía / supo',   'verb',         'She knew the answer immediately.',           'Ella supo la respuesta de inmediato.',        'NIUU'),

-- ─── A2: Lugares y preposiciones (76-90) ───────────────────
(76, 'park',       'parque',         'noun',         'We walk in the park on Sundays.',            'Caminamos en el parque los domingos.',        'PARK'),
(77, 'hospital',   'hospital',       'noun',         'The hospital is near the center.',           'El hospital está cerca del centro.',          'JOS-pi-tal'),
(78, 'school',     'escuela',        'noun',         'My school is five minutes away.',            'Mi escuela está a cinco minutos.',            'SKUUL'),
(79, 'store',      'tienda',         'noun',         'There is a store on the corner.',            'Hay una tienda en la esquina.',              'STOR'),
(80, 'bank',       'banco',          'noun',         'The bank opens at nine.',                    'El banco abre a las nueve.',                  'BANK'),
(81, 'next to',    'junto a',        'preposition',  'The café is next to the bank.',              'La cafetería está junto al banco.',           'NEXT-tu'),
(82, 'across from','frente a',       'preposition',  'The park is across from the school.',        'El parque está frente a la escuela.',         'a-KROS-from'),
(83, 'between',    'entre',          'preposition',  'The pharmacy is between the stores.',        'La farmacia está entre las tiendas.',         'bi-TUIIN'),
(84, 'near',       'cerca de',       'preposition',  'Is there a taxi near here?',                 '¿Hay un taxi cerca de aquí?',                 'NIR'),
(85, 'far',        'lejos',          'adjective',    'The airport is far from the center.',        'El aeropuerto está lejos del centro.',        'FAR'),
(86, 'left',       'izquierda',      'noun',         'Turn left at the traffic light.',            'Dobla a la izquierda en el semáforo.',        'LEFT'),
(87, 'right',      'derecha',        'noun',         'The hotel is on the right.',                 'El hotel está a la derecha.',                 'RAIT'),
(88, 'straight',   'recto / derecho','adverb',       'Go straight for two blocks.',                'Ve recto dos cuadras.',                      'STREIT'),
(89, 'corner',     'esquina',        'noun',         'Meet me at the corner.',                     'Encuéntrate conmigo en la esquina.',         'KOR-ner'),
(90, 'block',      'cuadra / bloque','noun',         'The restaurant is two blocks away.',         'El restaurante está a dos cuadras.',          'BLOK'),

-- ─── A2: Emociones y estados (91-105) ──────────────────────
(91,  'happy',     'feliz',          'adjective',    'I feel happy when I learn new things.',      'Me siento feliz cuando aprendo cosas nuevas.','JA-pi'),
(92,  'sad',       'triste',         'adjective',    'She felt sad after the movie.',              'Ella se sintió triste después de la película.','SAD'),
(93,  'tired',     'cansado',        'adjective',    'I am tired after work.',                     'Estoy cansada después del trabajo.',          'TAID'),
(94,  'excited',   'emocionado',     'adjective',    'He is excited about his trip.',              'Él está emocionado con su viaje.',            'ek-SAIT-ed'),
(95,  'worried',   'preocupado',     'adjective',    'She is worried about the exam.',             'Ella está preocupada por el examen.',         'UO-rid'),
(96,  'angry',     'enojado',        'adjective',    'He gets angry when people are late.',        'Se enoja cuando la gente llega tarde.',      'AN-gri'),
(97,  'surprised', 'sorprendido',    'adjective',    'I was surprised by the news.',               'Me sorprendieron las noticias.',              'ser-PRAIZD'),
(98,  'nervous',   'nervioso',       'adjective',    'She felt nervous before the presentation.',  'Ella se sintió nerviosa antes de la presentación.','NER-ves'),
(99,  'bored',     'aburrido',       'adjective',    'He was bored during the meeting.',           'Él se aburrió durante la reunión.',           'BORD'),
(100, 'proud',     'orgulloso',      'adjective',    'She is proud of her daughter.',              'Ella está orgullosa de su hija.',             'PRAUD'),
(101, 'lonely',    'solo / solitario','adjective',   'He felt lonely in the new city.',            'Se sintió solo en la nueva ciudad.',          'LOUN-li'),
(102, 'calm',      'tranquilo',      'adjective',    'Stay calm and take a deep breath.',          'Mantén la calma y respira profundo.',         'KALM'),
(103, 'confident', 'seguro de sí mismo','adjective', 'She feels confident speaking English now.',  'Ahora se siente segura hablando inglés.',    'KON-fi-dent'),
(104, 'grateful',  'agradecido',     'adjective',    'I am grateful for every opportunity.',       'Estoy agradecida por cada oportunidad.',     'GREIT-ful'),
(105, 'hopeful',   'esperanzado',    'adjective',    'We are hopeful about the future.',           'Tenemos esperanza en el futuro.',            'JOUP-ful'),

-- ─── A2: Clima y naturaleza (106-120) ──────────────────────
(106, 'sunny',     'soleado',        'adjective',    'It is sunny and warm today.',                'Hoy hace sol y calor.',                      'SA-ni'),
(107, 'rainy',     'lluvioso',       'adjective',    'I do not like rainy days.',                  'No me gustan los días lluviosos.',           'REI-ni'),
(108, 'cold',      'frío',           'adjective',    'It is very cold in December.',               'Hace mucho frío en diciembre.',              'KOLD'),
(109, 'hot',       'caliente / calor','adjective',   'The summer is very hot here.',               'El verano es muy caluroso aquí.',            'JOT'),
(110, 'windy',     'ventoso',        'adjective',    'It is too windy to go out.',                 'Hace demasiado viento para salir.',          'WIN-di'),
(111, 'cloudy',    'nublado',        'adjective',    'The sky is cloudy this morning.',            'El cielo está nublado esta mañana.',         'KLAU-di'),
(112, 'rain',      'lluvia',         'noun',         'The rain helps the flowers grow.',           'La lluvia ayuda a crecer las flores.',       'REIN'),
(113, 'sun',       'sol',            'noun',         'The sun sets at seven today.',               'El sol se pone a las siete hoy.',            'SON'),
(114, 'wind',      'viento',         'noun',         'The wind is strong today.',                  'El viento está fuerte hoy.',                 'UIND'),
(115, 'snow',      'nieve',          'noun',         'Children love to play in the snow.',         'Los niños adoran jugar en la nieve.',        'SNOU'),
(116, 'tree',      'árbol',          'noun',         'There is a big tree in the yard.',           'Hay un árbol grande en el patio.',           'TRII'),
(117, 'flower',    'flor',           'noun',         'She gave me a beautiful flower.',            'Ella me dio una flor preciosa.',             'FLAU-er'),
(118, 'river',     'río',            'noun',         'We swam in the river last summer.',          'Nadamos en el río el verano pasado.',        'RI-ver'),
(119, 'mountain',  'montaña',        'noun',         'The mountains are covered in snow.',         'Las montañas están cubiertas de nieve.',     'MAUN-ten'),
(120, 'beach',     'playa',          'noun',         'We spend summer at the beach.',              'Pasamos el verano en la playa.',             'BIICH'),

-- ─── B1: Verbos modales y condicionales (121-140) ──────────
(121, 'should',    'debería',        'verb',         'You should drink more water.',               'Deberías beber más agua.',                   'ŠUUD'),
(122, 'could',     'podría',         'verb',         'Could you help me with this?',               '¿Podrías ayudarme con esto?',               'KUD'),
(123, 'would',     'quisiera',       'verb',         'I would like a coffee, please.',             'Quisiera un café, por favor.',              'WUD'),
(124, 'might',     'podría (quizás)','verb',         'It might rain this afternoon.',              'Podría llover esta tarde.',                  'MAIT'),
(125, 'must',      'deber (obligación)','verb',      'You must wear a seatbelt.',                  'Debes usar el cinturón de seguridad.',       'MAST'),
(126, 'if',        'si (condicional)','conjunction', 'If I study hard, I will pass.',             'Si estudio mucho, voy a pasar.',            'IF'),
(127, 'unless',    'a menos que',    'conjunction',  'I will go unless it rains.',                 'Iré a menos que llueva.',                    'on-LES'),
(128, 'although',  'aunque',         'conjunction',  'Although it was hard, she did it.',          'Aunque fue difícil, ella lo logró.',        'ol-DOU'),
(129, 'however',   'sin embargo',    'adverb',       'The test was hard. However, I passed.',      'El examen fue difícil. Sin embargo, pasé.', 'JAU-e-ver'),
(130, 'therefore', 'por lo tanto',   'adverb',       'She studied hard; therefore, she passed.',   'Ella estudió mucho; por lo tanto, pasó.',   'DER-for'),
(131, 'moreover',  'además',         'adverb',       'It is fast. Moreover, it is cheap.',         'Es rápido. Además, es barato.',             'mor-O-ver'),
(132, 'instead',   'en cambio / en su lugar','adverb','Instead of coffee, I drank tea.',           'En lugar de café, tomé té.',                'in-STED'),
(133, 'despite',   'a pesar de',     'preposition',  'Despite the rain, we played outside.',       'A pesar de la lluvia, jugamos afuera.',     'dis-PAIT'),
(134, 'unless',    'a menos que',    'conjunction',  'Call me unless you are busy.',               'Llámame a menos que estés ocupada.',        'on-LES'),
(135, 'as long as','siempre que',    'phrase',       'As long as you try, you will improve.',      'Siempre que lo intentes, mejorarás.',       'as-LONG-as'),
(136, 'in case',   'por si acaso',   'phrase',       'Take an umbrella in case it rains.',         'Lleva un paraguas por si acaso llueve.',    'in-KEIS'),
(137, 'wish',      'desear',         'verb',         'I wish I could travel the world.',           'Quisiera poder viajar por el mundo.',       'UISH'),
(138, 'hope',      'esperar / tener esperanza','verb','I hope you feel better soon.',              'Espero que te mejores pronto.',             'JOUP'),
(139, 'imagine',   'imaginar',       'verb',         'Imagine a world without borders.',           'Imagina un mundo sin fronteras.',           'i-MA-yin'),
(140, 'wonder',    'preguntarse',    'verb',         'I wonder what the future holds.',            'Me pregunto qué nos depara el futuro.',     'UON-der'),

-- ─── B1: Trabajo y estudios (141-160) ──────────────────────
(141, 'job',       'trabajo / empleo','noun',        'She got a new job at a clinic.',             'Ella consiguió un nuevo trabajo en una clínica.','YOB'),
(142, 'career',    'carrera profesional','noun',     'He built a successful career in medicine.',  'Él construyó una carrera exitosa en medicina.','ka-RIR'),
(143, 'salary',    'salario',        'noun',         'The salary includes health benefits.',       'El salario incluye beneficios de salud.',    'SA-la-ri'),
(144, 'interview', 'entrevista',     'noun',         'She prepared well for the interview.',       'Ella se preparó bien para la entrevista.',  'IN-ter-viu'),
(145, 'deadline',  'fecha límite',   'noun',         'The deadline is this Friday.',               'La fecha límite es este viernes.',           'DED-lain'),
(146, 'team',      'equipo',         'noun',         'Our team works very well together.',         'Nuestro equipo trabaja muy bien en conjunto.','TIIM'),
(147, 'meeting',   'reunión',        'noun',         'We have a meeting at ten o''clock.',         'Tenemos una reunión a las diez.',            'MII-ting'),
(148, 'project',   'proyecto',       'noun',         'The project is due next month.',             'El proyecto vence el mes que viene.',        'PRO-yekt'),
(149, 'skill',     'habilidad',      'noun',         'Communication is an important skill.',      'La comunicación es una habilidad importante.','SKIL'),
(150, 'experience','experiencia',    'noun',         'She has five years of experience.',          'Ella tiene cinco años de experiencia.',      'ex-PIR-iens'),
(151, 'degree',    'título / grado', 'noun',         'He has a degree in engineering.',            'Él tiene un título en ingeniería.',          'di-GRII'),
(152, 'apply',     'solicitar / aplicar','verb',     'I want to apply for that position.',         'Quiero solicitar ese puesto.',              'a-PLAI'),
(153, 'improve',   'mejorar',        'verb',         'Practice every day to improve your English.','Practica todos los días para mejorar tu inglés.','im-PRUUV'),
(154, 'achieve',   'lograr',         'verb',         'You can achieve anything you set your mind to.','Puedes lograr todo lo que te propongas.',  'a-CHIIV'),
(155, 'manage',    'gestionar / manejar','verb',     'She manages a team of fifteen people.',      'Ella gestiona un equipo de quince personas.','MA-ney'),
(156, 'focus',     'enfocarse',      'verb',         'Try to focus on one task at a time.',        'Intenta enfocarte en una tarea a la vez.',  'FOU-kos'),
(157, 'present',   'presentar',      'verb',         'He presented the results to the board.',     'Él presentó los resultados a la junta.',    'pri-SENT'),
(158, 'report',    'informe / reportar','noun',      'The weekly report is due Monday.',           'El informe semanal vence el lunes.',         'ri-PORT'),
(159, 'feedback',  'retroalimentación','noun',       'Her feedback helped me improve a lot.',      'Su retroalimentación me ayudó a mejorar mucho.','FIID-bak'),
(160, 'colleague', 'colega',         'noun',         'My colleagues are very supportive.',         'Mis colegas son muy solidarios.',           'KO-liig'),

-- ─── B1: Viajes y turismo (161-180) ────────────────────────
(161, 'passport',  'pasaporte',      'noun',         'Do not forget your passport at home.',       'No olvides tu pasaporte en casa.',           'PAS-port'),
(162, 'flight',    'vuelo',          'noun',         'My flight leaves at six in the morning.',   'Mi vuelo sale a las seis de la mañana.',     'FLAIT'),
(163, 'luggage',   'equipaje',       'noun',         'The luggage is too heavy.',                  'El equipaje pesa demasiado.',                'LA-gey'),
(164, 'hotel',     'hotel',          'noun',         'The hotel has a beautiful pool.',            'El hotel tiene una piscina preciosa.',       'jo-TEL'),
(165, 'ticket',    'boleto',         'noun',         'I bought a round trip ticket.',              'Compré un boleto de ida y vuelta.',          'TI-ket'),
(166, 'reservation','reservación',   'noun',         'I have a reservation for two.',              'Tengo una reservación para dos.',            're-ser-VEI-šon'),
(167, 'customs',   'aduana',         'noun',         'We waited an hour at customs.',              'Esperamos una hora en la aduana.',           'KAS-toms'),
(168, 'currency',  'moneda / divisa','noun',         'What is the local currency here?',           '¿Cuál es la moneda local aquí?',             'KA-ren-si'),
(169, 'tour',      'recorrido / tour','noun',        'We took a tour of the old city.',            'Hicimos un recorrido por la ciudad vieja.',  'TUR'),
(170, 'guide',     'guía',           'noun',         'The guide explained the history well.',      'El guía explicó bien la historia.',          'GAID'),
(171, 'adventure', 'aventura',       'noun',         'Traveling is a great adventure.',            'Viajar es una gran aventura.',              'ad-VEN-cher'),
(172, 'explore',   'explorar',       'verb',         'We explored the local markets.',             'Exploramos los mercados locales.',           'ex-PLOR'),
(173, 'landmark',  'punto de referencia','noun',     'The Eiffel Tower is a famous landmark.',     'La Torre Eiffel es un punto de referencia famoso.','LAND-mark'),
(174, 'souvenir',  'recuerdo',       'noun',         'I bought souvenirs for my family.',          'Compré recuerdos para mi familia.',          'su-ve-NIR'),
(175, 'recommend', 'recomendar',     'verb',         'Can you recommend a good restaurant?',       '¿Puedes recomendar un buen restaurante?',   're-ko-MEND'),
(176, 'atmosphere','ambiente',       'noun',         'The café has a wonderful atmosphere.',       'La cafetería tiene un ambiente maravilloso.','AT-mos-fir'),
(177, 'local',     'local',          'adjective',    'We prefer eating at local restaurants.',     'Preferimos comer en restaurantes locales.',  'LOU-kal'),
(178, 'culture',   'cultura',        'noun',         'Every country has its unique culture.',      'Cada país tiene su cultura única.',          'KAL-cher'),
(179, 'tradition', 'tradición',      'noun',         'Day of the Dead is a Mexican tradition.',   'El Día de Muertos es una tradición mexicana.','tra-DI-šon'),
(180, 'border',    'frontera',       'noun',         'We crossed the border by car.',              'Cruzamos la frontera en carro.',            'BOR-der'),

-- ─── B1+: Habilidades blandas y comunicación (181-210) ─────
(181, 'communication','comunicación','noun',         'Good communication is key at work.',         'La buena comunicación es clave en el trabajo.','ko-miu-ni-KEI-šon'),
(182, 'listen',    'escuchar',       'verb',         'It is important to listen carefully.',       'Es importante escuchar con atención.',       'LI-son'),
(183, 'explain',   'explicar',       'verb',         'Can you explain that again, please?',        '¿Puedes explicar eso otra vez, por favor?',  'ex-PLEIN'),
(184, 'understand','entender',       'verb',         'I do not understand this grammar rule.',     'No entiendo esta regla gramatical.',         'an-der-STAND'),
(185, 'describe',  'describir',      'verb',         'Describe your ideal job in English.',        'Describe tu trabajo ideal en inglés.',       'des-KRAIB'),
(186, 'disagree',  'estar en desacuerdo','verb',     'It is okay to disagree respectfully.',       'Está bien estar en desacuerdo respetuosamente.','dis-a-GRII'),
(187, 'negotiate', 'negociar',       'verb',         'She negotiated a better salary.',            'Ella negoció un mejor salario.',            'ni-GOU-šieit'),
(188, 'persuade',  'persuadir',      'verb',         'He persuaded the team to try a new method.','Él persuadió al equipo de probar un nuevo método.','per-SUEID'),
(189, 'polite',    'cortés',         'adjective',    'Always be polite with customers.',           'Siempre sé cortés con los clientes.',        'po-LAIT'),
(190, 'honest',    'honesto',        'adjective',    'Honesty builds trust in relationships.',     'La honestidad construye confianza en las relaciones.','O-nest'),
(191, 'patient',   'paciente',       'adjective',    'Learning a language requires being patient.','Aprender un idioma requiere ser paciente.',  'PEI-šent'),
(192, 'creative',  'creativo',       'adjective',    'She found a creative solution to the problem.','Ella encontró una solución creativa al problema.','kri-EI-tiv'),
(193, 'flexible',  'flexible',       'adjective',    'You need to be flexible in a new job.',      'Necesitas ser flexible en un nuevo trabajo.','FLEK-si-bol'),
(194, 'organized', 'organizado',     'adjective',    'Being organized saves a lot of time.',       'Estar organizado ahorra mucho tiempo.',      'OR-ga-naizd'),
(195, 'reliable',  'confiable',      'adjective',    'She is one of our most reliable employees.','Ella es una de nuestras empleadas más confiables.','ri-LAI-a-bol'),
(196, 'empathy',   'empatía',        'noun',         'Empathy makes us better people.',            'La empatía nos hace mejores personas.',      'EM-pa-zi'),
(197, 'leadership','liderazgo',      'noun',         'Good leadership inspires the whole team.',   'El buen liderazgo inspira a todo el equipo.','LII-der-šip'),
(198, 'teamwork',  'trabajo en equipo','noun',       'Teamwork makes the dream work.',             'El trabajo en equipo hace realidad los sueños.','TIIM-uork'),
(199, 'deadline',  'plazo / fecha límite','noun',    'We always deliver before the deadline.',     'Siempre entregamos antes del plazo.',        'DED-lain'),
(200, 'priority',  'prioridad',      'noun',         'Learning English is my top priority.',       'Aprender inglés es mi prioridad principal.', 'prai-OR-i-ti'),
(201, 'goal',      'meta / objetivo','noun',         'Set a clear goal and work toward it.',       'Establece una meta clara y trabaja hacia ella.','GOUL'),
(202, 'challenge', 'reto / desafío', 'noun',         'Every challenge is an opportunity to grow.','Cada reto es una oportunidad para crecer.',  'CHA-ley'),
(203, 'solution',  'solución',       'noun',         'There is always a solution if you look hard.','Siempre hay una solución si buscas bien.',  'so-LUU-šon'),
(204, 'decision',  'decisión',       'noun',         'It was a difficult decision to make.',       'Fue una decisión difícil de tomar.',         'di-SI-šon'),
(205, 'progress',  'progreso',       'noun',         'I can see your progress every week.',        'Puedo ver tu progreso cada semana.',         'PRO-gres'),
(206, 'effort',    'esfuerzo',       'noun',         'Hard work and effort always pay off.',       'El trabajo duro y el esfuerzo siempre dan frutos.','E-fort'),
(207, 'attitude',  'actitud',        'noun',         'A positive attitude changes everything.',    'Una actitud positiva lo cambia todo.',       'A-ti-tuud'),
(208, 'mindset',   'mentalidad',     'noun',         'A growth mindset helps you learn faster.',   'Una mentalidad de crecimiento te ayuda a aprender más rápido.','MAIND-set'),
(209, 'balance',   'equilibrio',     'noun',         'Work-life balance is very important.',       'El equilibrio trabajo-vida es muy importante.','BA-lans'),
(210, 'routine',   'rutina',         'noun',         'A good routine sets you up for success.',    'Una buena rutina te prepara para el éxito.',  'ruu-TIIN'),

-- ─── B2: Expresiones complejas (211-250) ───────────────────
(211, 'come across','encontrarse con','phrase',      'I came across a great book yesterday.',      'Me topé con un gran libro ayer.',            'kam-a-KROS'),
(212, 'bring up',  'mencionar / sacar a tema','phrase','Do not bring up the past.',               'No saques el pasado a la conversación.',     'bring-AP'),
(213, 'put off',   'posponer',       'phrase',       'Stop putting off what you can do today.',    'Deja de posponer lo que puedes hacer hoy.',  'put-OF'),
(214, 'give up',   'rendirse',       'phrase',       'Never give up on your dreams.',              'Nunca te rindas con tus sueños.',            'giv-AP'),
(215, 'look up',   'buscar / consultar','phrase',    'Look up the word in the dictionary.',        'Busca la palabra en el diccionario.',        'luk-AP'),
(216, 'turn down', 'rechazar',       'phrase',       'She turned down the job offer.',             'Ella rechazó la oferta de trabajo.',         'tern-DAUN'),
(217, 'set up',    'configurar / establecer','phrase','He set up a new business last year.',       'Él estableció un nuevo negocio el año pasado.','set-AP'),
(218, 'carry out', 'llevar a cabo',  'phrase',       'The team carried out the plan perfectly.',   'El equipo llevó el plan a cabo perfectamente.','KA-ri-aut'),
(219, 'stand out', 'destacar',       'phrase',       'Her skills make her stand out.',             'Sus habilidades la hacen destacar.',         'stand-AUT'),
(220, 'catch up',  'ponerse al día', 'phrase',       'I need to catch up on my reading.',          'Necesito ponerme al día con mis lecturas.',  'kach-AP'),
(221, 'break down','desglosar / averiarse','phrase', 'Let me break down the problem for you.',     'Déjame desglosar el problema para ti.',     'breik-DAUN'),
(222, 'run out of','quedarse sin',   'phrase',       'We ran out of time in the meeting.',         'Se nos acabó el tiempo en la reunión.',     'ron-AUT-ov'),
(223, 'deal with', 'lidiar con',     'phrase',       'How do you deal with stress?',               '¿Cómo lidias con el estrés?',               'diil-WID'),
(224, 'end up',    'terminar / acabar','phrase',     'We ended up staying until midnight.',         'Terminamos quedándonos hasta la medianoche.','end-AP'),
(225, 'get along', 'llevarse bien',  'phrase',       'She gets along with everyone at work.',      'Ella se lleva bien con todos en el trabajo.','get-a-LONG'),
(226, 'point out', 'señalar',        'phrase',       'She pointed out an error in the report.',    'Ella señaló un error en el informe.',       'point-AUT'),
(227, 'figure out','descifrar / entender','phrase',  'I finally figured out how it works.',        'Por fin entendí cómo funciona.',            'FI-ger-aut'),
(228, 'hold on',   'espera / esperar','phrase',      'Hold on, I will be right back.',             'Espera, regreso en un momento.',            'JOLD-on'),
(229, 'take over', 'tomar el control','phrase',      'She took over the project last month.',      'Ella tomó el control del proyecto el mes pasado.','teik-OU-ver'),
(230, 'come up with','idear / ocurrirse','phrase',   'Can you come up with a better idea?',        '¿Se te puede ocurrir una mejor idea?',      'kam-AP-wid'),
(231, 'apparent',  'evidente / aparente','adjective','It is apparent that she works very hard.',   'Es evidente que ella trabaja muy duro.',     'a-PA-rent'),
(232, 'enhance',   'mejorar / realzar','verb',       'Exercise enhances your mood and focus.',     'El ejercicio mejora tu estado de ánimo y concentración.','en-JANS'),
(233, 'sustain',   'sostener / mantener','verb',     'We need to sustain this level of quality.',  'Necesitamos mantener este nivel de calidad.','sos-TEIN'),
(234, 'implement', 'implementar',    'verb',         'The company implemented new procedures.',    'La empresa implementó nuevos procedimientos.','IM-plo-ment'),
(235, 'evaluate',  'evaluar',        'verb',         'We need to evaluate all the options.',       'Necesitamos evaluar todas las opciones.',    'i-VAL-yu-eit'),
(236, 'analyse',   'analizar',       'verb',         'Analyse the data before making a decision.','Analiza los datos antes de tomar una decisión.','A-na-laiz'),
(237, 'crucial',   'crucial',        'adjective',    'This step is crucial for success.',          'Este paso es crucial para el éxito.',        'KRUU-šal'),
(238, 'significant','significativo',  'adjective',   'The results show a significant improvement.','Los resultados muestran una mejora significativa.','sig-NI-fi-kant'),
(239, 'diverse',   'diverso',        'adjective',    'Our team is very diverse and talented.',     'Nuestro equipo es muy diverso y talentoso.','dai-VERS'),
(240, 'sustainable','sostenible',    'adjective',    'We need more sustainable energy sources.',   'Necesitamos fuentes de energía más sostenibles.','sos-TEI-na-bol'),

-- ─── B2: Vocabulario académico y profesional (241-300) ─────
(241, 'hypothesis','hipótesis',      'noun',         'The hypothesis was proven correct.',         'La hipótesis resultó ser correcta.',         'jai-PO-ze-sis'),
(242, 'evidence',  'evidencia',      'noun',         'There is strong evidence for this theory.',  'Hay evidencia sólida de esta teoría.',       'E-vi-dens'),
(243, 'conclude',  'concluir',       'verb',         'We can conclude that practice works.',       'Podemos concluir que la práctica funciona.', 'kon-KLUUD'),
(244, 'argue',     'argumentar',     'verb',         'She argued that the plan needed changes.',   'Ella argumentó que el plan necesitaba cambios.','AR-giuu'),
(245, 'assumption','suposición',     'noun',         'Do not make assumptions without data.',      'No hagas suposiciones sin datos.',           'a-SOM-šon'),
(246, 'context',   'contexto',       'noun',         'Always read words in their context.',        'Siempre lee las palabras en su contexto.',   'KON-tekst'),
(247, 'relevant',  'relevante',      'adjective',    'Include only relevant information.',         'Incluye solo información relevante.',        'RE-le-vant'),
(248, 'accurate',  'preciso / exacto','adjective',   'Make sure your data is accurate.',           'Asegúrate de que tus datos sean precisos.',  'A-kiu-ret'),
(249, 'complex',   'complejo',       'adjective',    'The problem is more complex than it seems.', 'El problema es más complejo de lo que parece.','KOM-pleks'),
(250, 'abstract',  'abstracto / resumen','adjective','Write a short abstract for your paper.',     'Escribe un resumen breve para tu trabajo.',  'AB-strakt'),
(251, 'framework', 'marco / estructura','noun',      'We need a clear framework to follow.',       'Necesitamos un marco claro a seguir.',       'FREIM-uork'),
(252, 'outcome',   'resultado / desenlace','noun',   'The outcome exceeded our expectations.',     'El resultado superó nuestras expectativas.', 'AUT-kam'),
(253, 'impact',    'impacto',        'noun',         'This decision will have a major impact.',    'Esta decisión tendrá un gran impacto.',      'IM-pakt'),
(254, 'strategy',  'estrategia',     'noun',         'We need a strategy to reach our goals.',     'Necesitamos una estrategia para alcanzar nuestras metas.','STRA-te-yi'),
(255, 'resource',  'recurso',        'noun',         'Time is our most valuable resource.',        'El tiempo es nuestro recurso más valioso.',  'RII-sors'),
(256, 'initiative','iniciativa',     'noun',         'She took the initiative to lead the group.','Ella tomó la iniciativa de liderar el grupo.','i-NI-šia-tiv'),
(257, 'contribute','contribuir',     'verb',         'Everyone can contribute to the project.',    'Todos pueden contribuir al proyecto.',       'kon-TRI-biut'),
(258, 'collaborate','colaborar',     'verb',         'The teams collaborated across departments.','Los equipos colaboraron entre departamentos.','ko-LA-bo-reit'),
(259, 'innovate',  'innovar',        'verb',         'Companies must innovate to stay competitive.','Las empresas deben innovar para mantenerse competitivas.','I-no-veit'),
(260, 'transform', 'transformar',    'verb',         'Technology has transformed the way we work.','La tecnología ha transformado la forma en que trabajamos.','trans-FORM'),
(261, 'consistency','consistencia',  'noun',         'Consistency is the key to mastering a language.','La consistencia es la clave para dominar un idioma.','kon-SIS-ten-si'),
(262, 'perspective','perspectiva',   'noun',         'Try to see things from a different perspective.','Intenta ver las cosas desde otra perspectiva.','per-SPEK-tiv'),
(263, 'interpret', 'interpretar',    'verb',         'How do you interpret this sentence?',        '¿Cómo interpretas esta oración?',            'in-TER-prit'),
(264, 'convey',    'transmitir / expresar','verb',   'She conveyed her ideas clearly.',            'Ella transmitió sus ideas con claridad.',    'kon-VEI'),
(265, 'imply',     'implicar / insinuar','verb',     'What does this sentence imply?',             '¿Qué implica esta oración?',                 'im-PLAI'),
(266, 'emphasize', 'enfatizar',      'verb',         'She emphasized the importance of practice.',  'Ella enfatizó la importancia de la práctica.','EM-fa-saiz'),
(267, 'clarify',   'aclarar',        'verb',         'Could you clarify what you mean?',           '¿Podrías aclarar lo que quieres decir?',     'KLA-ri-fai'),
(268, 'summarize', 'resumir',        'verb',         'Can you summarize the main points?',         '¿Puedes resumir los puntos principales?',    'SA-ma-raiz'),
(269, 'elaborate', 'desarrollar / ampliar','verb',  'Please elaborate on your last point.',        'Por favor desarrolla tu último punto.',      'i-LA-bo-reit'),
(270, 'justify',   'justificar',     'verb',         'Justify your answer with examples.',         'Justifica tu respuesta con ejemplos.',       'YOS-ti-fai'),
(271, 'obtain',    'obtener',        'verb',         'How can I obtain more information?',         '¿Cómo puedo obtener más información?',      'ob-TEIN'),
(272, 'maintain',  'mantener',       'verb',         'It is hard to maintain motivation every day.','Es difícil mantener la motivación todos los días.','mein-TEIN'),
(273, 'establish', 'establecer',     'verb',         'They established a new company last year.',  'Establecieron una nueva empresa el año pasado.','es-TA-bliš'),
(274, 'generate',  'generar',        'verb',         'This app generates a lot of useful data.',   'Esta app genera muchos datos útiles.',       'YE-ne-reit'),
(275, 'indicate',  'indicar',        'verb',         'The results indicate a clear improvement.',  'Los resultados indican una mejora clara.',   'IN-di-keit'),
(276, 'promote',   'promover',       'verb',         'She was promoted after six months.',         'Ella fue ascendida después de seis meses.',  'pro-MOUT'),
(277, 'restrict',  'restringir',     'verb',         'Access is restricted to authorized users.',  'El acceso está restringido a usuarios autorizados.','ris-TRIKT'),
(278, 'expand',    'expandir',       'verb',         'The company plans to expand next year.',     'La empresa planea expandirse el próximo año.','ex-PAND'),
(279, 'monitor',   'monitorear',     'verb',         'We monitor student progress weekly.',        'Monitoreamos el progreso del estudiante semanalmente.','MO-ni-tor'),
(280, 'propose',   'proponer',       'verb',         'He proposed a new solution to the problem.','Él propuso una nueva solución al problema.',  'pro-POUZ'),
(281, 'concept',   'concepto',       'noun',         'This concept is easy once you understand it.','Este concepto es fácil una vez que lo entiendes.','KON-sept'),
(282, 'principle', 'principio',      'noun',         'Always work by your principles.',            'Siempre trabaja según tus principios.',      'PRIN-si-pol'),
(283, 'approach',  'enfoque / método','noun',        'Try a different approach to the problem.',   'Prueba un enfoque diferente para el problema.','a-PROUCH'),
(284, 'factor',    'factor',         'noun',         'Many factors affect language learning.',     'Muchos factores afectan el aprendizaje de idiomas.','FAK-tor'),
(285, 'trend',     'tendencia',      'noun',         'Remote work is a growing trend.',            'El trabajo remoto es una tendencia creciente.','TREND'),
(286, 'awareness', 'conciencia',     'noun',         'Awareness of your mistakes helps you grow.','La conciencia de tus errores te ayuda a crecer.','a-UER-nes'),
(287, 'commitment','compromiso',     'noun',         'Success requires commitment and effort.',    'El éxito requiere compromiso y esfuerzo.',   'ko-MIT-ment'),
(288, 'integrity', 'integridad',     'noun',         'She is known for her integrity.',            'Ella es conocida por su integridad.',        'in-TE-gri-ti'),
(289, 'influence', 'influencia',     'noun',         'Music has a big influence on our mood.',     'La música tiene una gran influencia en nuestro estado de ánimo.','IN-flu-ens'),
(290, 'potential', 'potencial',      'noun',         'You have the potential to be great.',        'Tienes el potencial para ser grandiosa.',   'po-TEN-šal'),
(291, 'ambition',  'ambición',       'noun',         'Her ambition drove her to succeed.',         'Su ambición la llevó al éxito.',            'am-BI-šon'),
(292, 'resilient', 'resiliente',     'adjective',    'She remained resilient through every challenge.','Ella se mantuvo resiliente ante cada reto.','ri-ZI-lient'),
(293, 'persistent','persistente',    'adjective',    'Be persistent and you will see results.',    'Sé persistente y verás resultados.',         'per-SIS-tent'),
(294, 'dedicated', 'dedicado',       'adjective',    'He is very dedicated to his studies.',       'Él está muy dedicado a sus estudios.',       'DE-di-kei-ted'),
(295, 'motivated', 'motivado',       'adjective',    'Staying motivated is key to reaching goals.','Mantenerse motivado es clave para alcanzar metas.','MOU-ti-vei-ted'),
(296, 'determined','determinado',    'adjective',    'She was determined to learn English.',        'Ella estaba decidida a aprender inglés.',   'di-TER-mind'),
(297, 'ambitious', 'ambicioso',      'adjective',    'Being ambitious means working hard for more.','Ser ambicioso significa trabajar duro por más.','am-BI-šos'),
(298, 'innovative','innovador',      'adjective',    'The company has an innovative culture.',     'La empresa tiene una cultura innovadora.',  'I-no-vei-tiv'),
(299, 'versatile', 'versátil',       'adjective',    'She is a versatile professional.',           'Ella es una profesional versátil.',          'VER-sa-til'),
(300, 'exceptional','excepcional',   'adjective',    'Her performance was truly exceptional.',     'Su desempeño fue verdaderamente excepcional.','ex-SEP-šo-nal'),

-- ─── B2+: Vocabulario profesional avanzado (301-365) ───────
(301, 'accomplish','lograr / cumplir','verb',        'She accomplished her goal in record time.',  'Ella cumplió su meta en tiempo récord.',     'a-KOM-pliš'),
(302, 'anticipate','anticipar',      'verb',         'We must anticipate problems before they arise.','Debemos anticipar los problemas antes de que surjan.','an-TI-si-peit'),
(303, 'articulate','articular / expresar','verb',    'She articulates her ideas very clearly.',    'Ella articula sus ideas con mucha claridad.','ar-TI-kiu-let'),
(304, 'capacity',  'capacidad',      'noun',         'The stadium has a capacity of fifty thousand.','El estadio tiene una capacidad de cincuenta mil.','ka-PA-si-ti'),
(305, 'catalyst',  'catalizador',    'noun',         'Her speech was a catalyst for change.',      'Su discurso fue un catalizador del cambio.', 'KA-ta-list'),
(306, 'coherent',  'coherente',      'adjective',    'Make sure your argument is coherent.',       'Asegúrate de que tu argumento sea coherente.','ko-JIR-ent'),
(307, 'constraint','restricción / limitación','noun','Budget constraints forced us to adapt.',     'Las restricciones presupuestales nos forzaron a adaptarnos.','kon-STREINT'),
(308, 'criteria',  'criterios',      'noun',         'What are the criteria for this decision?',   '¿Cuáles son los criterios para esta decisión?','krai-TIR-ia'),
(309, 'delegate',  'delegar',        'verb',         'A good leader knows how to delegate.',       'Un buen líder sabe delegar.',               'DE-le-geit'),
(310, 'diagnose',  'diagnosticar',   'verb',         'The doctor diagnosed the problem quickly.',  'El doctor diagnosticó el problema rápido.',  'dai-ag-NOUZ'),
(311, 'dilemma',   'dilema',         'noun',         'She faced a difficult dilemma at work.',     'Ella enfrentó un difícil dilema en el trabajo.','di-LE-ma'),
(312, 'distinct',  'distinto',       'adjective',    'Each student has a distinct learning style.','Cada estudiante tiene un estilo de aprendizaje distinto.','dis-TIKT'),
(313, 'dynamic',   'dinámico',       'adjective',    'The job market is very dynamic now.',        'El mercado laboral es muy dinámico ahora.',  'dai-NA-mik'),
(314, 'efficient', 'eficiente',      'adjective',    'She found a more efficient way to study.',   'Ella encontró una manera más eficiente de estudiar.','i-FI-šent'),
(315, 'eliminate', 'eliminar',       'verb',         'We need to eliminate unnecessary steps.',    'Necesitamos eliminar los pasos innecesarios.','i-LI-mi-neit'),
(316, 'engage',    'involucrar / comprometer','verb','How do you engage your team effectively?',   '¿Cómo involucras a tu equipo de manera efectiva?','en-GEICH'),
(317, 'enhance',   'mejorar / potenciar','verb',     'Reading enhances your vocabulary greatly.',  'Leer potencia mucho tu vocabulario.',        'en-JANS'),
(318, 'evident',   'evidente',       'adjective',    'It is evident that she works very hard.',    'Es evidente que ella trabaja muy duro.',     'E-vi-dent'),
(319, 'expertise', 'experiencia / conocimiento experto','noun','Her expertise is in financial analysis.','Su experiencia es en análisis financiero.','ex-PER-tiiz'),
(320, 'facilitate','facilitar',      'verb',         'Technology facilitates communication.',      'La tecnología facilita la comunicación.',    'fa-SI-li-teit'),
(321, 'fundamental','fundamental',   'adjective',    'Grammar is fundamental to communication.',   'La gramática es fundamental para la comunicación.','fan-da-MEN-tal'),
(322, 'generate',  'generar',        'verb',         'Good ideas generate better opportunities.',  'Las buenas ideas generan mejores oportunidades.','YE-ne-reit'),
(323, 'genuine',   'genuino',        'adjective',    'Her interest in learning is genuine.',       'Su interés por aprender es genuino.',        'YE-niu-in'),
(324, 'highlight', 'destacar / resaltar','verb',     'She highlighted the key points of the talk.','Ella resaltó los puntos clave de la charla.','JAI-lait'),
(325, 'implement', 'poner en práctica','verb',       'We implemented the changes last quarter.',   'Pusimos en práctica los cambios el trimestre pasado.','IM-pli-ment'),
(326, 'implication','implicación',   'noun',         'What are the implications of this choice?',  '¿Cuáles son las implicaciones de esta elección?','im-pli-KEI-šon'),
(327, 'inherent',  'inherente',      'adjective',    'There is an inherent beauty in languages.',  'Hay una belleza inherente en los idiomas.',  'in-JIR-ent'),
(328, 'insight',   'perspicacia / visión','noun',    'She offered a valuable insight on the topic.','Ella ofreció una valiosa perspectiva sobre el tema.','IN-sait'),
(329, 'inspire',   'inspirar',       'verb',         'Great teachers inspire their students.',     'Los grandes maestros inspiran a sus alumnos.','in-SPAIR'),
(330, 'integrate', 'integrar',       'verb',         'You should integrate new words into your speech.','Deberías integrar palabras nuevas en tu discurso.','IN-te-greit'),
(331, 'justify',   'justificar',     'verb',         'Can you justify your decision?',             '¿Puedes justificar tu decisión?',           'YAS-ti-fai'),
(332, 'leverage',  'aprovechar',     'verb',         'Leverage your strengths to grow faster.',    'Aprovecha tus fortalezas para crecer más rápido.','LE-ve-rey'),
(333, 'logical',   'lógico',         'adjective',    'Her argument was clear and logical.',        'Su argumento fue claro y lógico.',           'LO-yi-kal'),
(334, 'mentor',    'mentor',         'noun',         'Find a mentor who inspires you.',            'Encuentra un mentor que te inspire.',        'MEN-tor'),
(335, 'modify',    'modificar',      'verb',         'We modified the plan based on feedback.',    'Modificamos el plan basándonos en la retroalimentación.','MO-di-fai'),
(336, 'motivate',  'motivar',        'verb',         'She motivates everyone around her.',         'Ella motiva a todos a su alrededor.',        'MOU-ti-veit'),
(337, 'navigate',  'navegar / desenvolverse','verb', 'She navigated the new system quickly.',      'Ella se desenvolvió rápido con el nuevo sistema.','NA-vi-geit'),
(338, 'negotiate', 'negociar',       'verb',         'We need to negotiate better terms.',         'Necesitamos negociar mejores condiciones.',  'ni-GOU-šieit'),
(339, 'objective', 'objetivo',       'noun',         'The main objective is clear communication.','El objetivo principal es la comunicación clara.','ob-YEK-tiv'),
(340, 'observe',   'observar',       'verb',         'Observe how native speakers use the language.','Observa cómo los hablantes nativos usan el idioma.','ob-SERV'),
(341, 'optimize',  'optimizar',      'verb',         'She optimized the process to save time.',    'Ella optimizó el proceso para ahorrar tiempo.','OP-ti-maiz'),
(342, 'overcome',  'superar',        'verb',         'She overcame her fear of speaking.',         'Ella superó su miedo a hablar.',            'ou-ver-KAM'),
(343, 'persist',   'persistir',      'verb',         'Persist even when things get hard.',         'Persiste incluso cuando las cosas se ponen difíciles.','per-SIST'),
(344, 'practical', 'práctico',       'adjective',    'Give practical examples when you explain.',  'Da ejemplos prácticos cuando expliques.',    'PRAK-ti-kal'),
(345, 'precise',   'preciso',        'adjective',    'Be precise when giving instructions.',       'Sé precisa cuando des instrucciones.',       'pri-SAIS'),
(346, 'predict',   'predecir',       'verb',         'Can you predict what happens next?',         '¿Puedes predecir qué sucede después?',      'pri-DIKT'),
(347, 'process',   'proceso',        'noun',         'Trust the process and be consistent.',       'Confía en el proceso y sé constante.',       'PRO-ses'),
(348, 'professional','profesional',  'adjective',    'She always behaves in a professional way.',  'Ella siempre se comporta de manera profesional.','pro-FE-šo-nal'),
(349, 'respond',   'responder',      'verb',         'Always respond within 24 hours.',            'Siempre responde en un máximo de 24 horas.','ri-SPOND'),
(350, 'reward',    'recompensa / recompensar','noun','Hard work brings its own reward.',           'El trabajo duro trae su propia recompensa.', 'ri-UORD'),
(351, 'sequence',  'secuencia',      'noun',         'Follow the sequence step by step.',          'Sigue la secuencia paso a paso.',            'SII-kwens'),
(352, 'simplify',  'simplificar',    'verb',         'Try to simplify complex ideas.',             'Intenta simplificar las ideas complejas.',   'SIM-pli-fai'),
(353, 'specific',  'específico',     'adjective',    'Be specific about what you need.',           'Sé específica sobre lo que necesitas.',      'spe-SI-fik'),
(354, 'spontaneous','espontáneo',    'adjective',    'Try to have spontaneous conversations.',     'Intenta tener conversaciones espontáneas.',  'spon-TEI-nios'),
(355, 'strengthen','fortalecer',     'verb',         'Reading every day strengthens your English.','Leer todos los días fortalece tu inglés.',   'STRENG-zen'),
(356, 'structure', 'estructura',     'noun',         'A clear structure helps your reader follow.','Una estructura clara ayuda al lector a seguirte.','STRAK-cher'),
(357, 'systematic','sistemático',    'adjective',    'A systematic approach works best for me.',   'Un enfoque sistemático funciona mejor para mí.','sis-te-MA-tik'),
(358, 'thorough',  'exhaustivo / minucioso','adjective','She did a thorough review of the contract.','Ella hizo una revisión exhaustiva del contrato.','ZA-ro'),
(359, 'transfer',  'transferir / aplicar','verb',    'Transfer what you learn to real conversations.','Aplica lo que aprendes a conversaciones reales.','TRANS-fer'),
(360, 'transparent','transparente',  'adjective',    'Be transparent about your goals.',           'Sé transparente sobre tus metas.',           'trans-PA-rent'),
(361, 'unique',    'único',          'adjective',    'Everyone has a unique way of learning.',     'Cada persona tiene una manera única de aprender.','yu-NIIK'),
(362, 'validate',  'validar',        'verb',         'Validate your ideas with evidence.',         'Valida tus ideas con evidencia.',            'VA-li-deit'),
(363, 'valuable',  'valioso',        'adjective',    'Every mistake is a valuable lesson.',        'Cada error es una valiosa lección.',         'VA-liu-bol'),
(364, 'vision',    'visión',         'noun',         'Her vision helped her build a great career.','Su visión le ayudó a construir una gran carrera.','VI-žon'),
(365, 'wisdom',    'sabiduría',      'noun',         'Wisdom comes from experience and reflection.','La sabiduría viene de la experiencia y la reflexión.','UIZ-dom');
